// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertVtt(arg1, arg2) {
  return window['go']['main']['App']['ConvertVtt'](arg1, arg2);
}

export function Log(arg1, arg2) {
  return window['go']['main']['App']['Log'](arg1, arg2);
}

export function RecycleFiles(arg1) {
  return window['go']['main']['App']['RecycleFiles'](arg1);
}

export function ScanByExt(arg1, arg2) {
  return window['go']['main']['App']['ScanByExt'](arg1, arg2);
}

export function ScanDropped(arg1, arg2, arg3) {
  return window['go']['main']['App']['ScanDropped'](arg1, arg2, arg3);
}

export function ScanFiles(arg1) {
  return window['go']['main']['App']['ScanFiles'](arg1);
}

export function SelectDir() {
  return window['go']['main']['App']['SelectDir']();
}
