// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConvertVtt(arg1:string,arg2:boolean):Promise<string>;

export function Log(arg1:string,arg2:string):Promise<void>;

export function RecycleFiles(arg1:Array<string>):Promise<number>;

export function ScanByExt(arg1:string,arg2:string):Promise<Array<main.FileStat>>;

export function ScanDropped(arg1:Array<string>,arg2:string,arg3:string):Promise<Array<main.FileStat>>;

export function ScanFiles(arg1:string):Promise<Array<main.FileStat>>;

export function SelectDir():Promise<string>;
